version: '3'
services:
    # this client serves javascript client in dev mode. it will proxy api requests to doom-client
    dev-client:
        build: ../../doom-client
        volumes:
        - ../../doom-client/src:/src
        command: ["npm", "run", "serve"]
        ports:
        - "8080:8080"
        environment:
        - HOST=0.0.0.0
        - PORT=8080
    doom-client:
        build: ../../doom-client
        ports:
        - "8081:8080"
        environment:
        - "DOOM_STATE_SERVICE_URL=http://doom-state:8080"
        - "DOOM_ENGINE_SERVICE_URL=http://doom-engine:8080"
        - "DOOM_STATE_SERVICE_PASSWORD=clientpwd"
    doom-engine:
        build: ../../doom-engine
        ports:
        - "8082:8080"
        environment:
        - "DOOM_STATE_SERVICE_URL=http://doom-state:8080"
        - "DOOM_STATE_SERVICE_PASSWORD=enginepwd"
    doom-state:
        build: ../../doom-state
        ports:
        - "8083:8080"